// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.jsf;

import com.school.jsf.TimerBean;
import java.io.Serializable;

privileged aspect TimerBean_Roo_Serializable {
    
    declare parents: TimerBean implements Serializable;
    
    private static final long TimerBean.serialVersionUID = 1L;
    
}
